
title: O2C Opendoc Theme
description: O2C tailored Jekyll Theme for Opendocs
plugins:
  - jekyll-include-cache
baseurl: ''
kramdown:
  auto_id_stripping: true
repository: jarekglapski/opendoc-theme
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg

fast_build: false
offline: false
preload_pages: true

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

google_analytics: ''
styling_options:
  primary_brand_color: '#17335f'
  logo_path: /assets/images/logo-order2cash.svg
  logo_url: https://order2cash.com
  feedback_url: https://www.order2cash.com/about-us/contact-form/

folders:
  - name: '/'
    title: 'Intro'
    subtitle: this is a subtitle
  - name: 'Document 1'
    title: 'test title'
    order:
      - contribute.md
      - introduction.md
