
title: Opendoc Theme
description: Jekyll Theme for Opendocs
plugins:
  - jekyll-include-cache
baseurl: ''
kramdown:
  auto_id_stripping: true
repository: opendocsg/opendoc-theme
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg

fast_build: true
offline: false
preload_pages: true

hide_toolbar:
  sidebar: false
  pdf: false
  github: false

google_analytics: 'UA-113717369-5'
styling_options:
  primary_brand_color: '#17335f'
  logo_path: /assets/images/opendoc-logo-full.svg
  logo_url: https://opendoc.sg
  feedback_url: null

folders:
  - name: '/'
    title: 'something'
    subtitle: this is a subtitle
    order:
      - contribute.md
      - import-files.md
  - name: '2019_SGHC 120'
    title: 'Shanker Maghalingam v Public Prosecutor'
    subtitle: hello
    order:
      - contribute.md
      - import-files.md
      - report.md
  - name: 'Docu ment2'
    title: 'Document two'
    subtitle: 'something 2'
  - name: 'Document 1'
    title: 'jefiojweofjofjwoefj'
    order:
      - contribute.md
      - introduction.md
