
title: Opendoc Theme
description: Jekyll Theme for Opendocs
plugins:
  - jekyll-include-cache
baseurl: ''
kramdown:
  auto_id_stripping: true
repository: opendocsg/opendoc-theme
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg

fast_build: true
offline: false
preload_pages: true

hide_toolbar:
  sidebar: false
  pdf: false
  github: false

google_analytics: 'UA-113717369-5'
styling_options:
  primary_brand_color: '#17335f'
  logo_path: /assets/images/opendoc-logo-full.svg
  logo_url: https://opendoc.sg
  feedback_url: null

documents:
  - folder: '/'
    subtitle: this is a subtitle
    pages:
      - contribute.md
      - import-files.md
  - folder: 'Document_1'
    title: Document 1
    subtitle: hello
    pages:
      - contribute.md
      - import-files.md
      - hello 123123
  
