
title: Opendoc Theme
timezone: Asia/Singapore
repository: opendocsg/opendoc-theme
description: Jekyll Theme for Opendocs
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  #----> Optional, Google analytics ID

# Override config specifc to sharepoint
siteurl: https://[COMPANY_NAME].sharepoint.com
environment: sharepoint
destination: sharepoint
baseurl: 'https://test.sharepoint.com'

fast_build: false
offline: false
preload_pages: true

styling_options:
  primary_brand_color: '#17335f'
  logo_path: /assets/images/opendoc-logo-full.svg
  logo_url: https://opendoc.sg
  feedback_url: null

hide_toolbar:
  sidebar: false
  pdf: false
  github: false

folders:
  - name: '/'  #----> '/' for root documents
    title: 'something'
    subtitle: this is a subtitle
    order:
      - contribute.md
      - import-files.md
  - name: '2019_SGHC 120'
    title: 'Shanker Maghalingam v Public Prosecutor'
    subtitle: hello
    order:
      - contribute.md
      - import-files.md
      - report.md
  - name: 'Docu ment2'
    title: 'Document two'
    subtitle: 'something 2'
  - name: 'Document 1'
    title: 'jefiojweofjofjwoefj'
    order:
      - contribute.md
      - introduction.md
